### ISSUE TITLE
Tautulli: DioError for Flutter web

### ISSUE THREAD

**Issue by strenkml** [CometTools/Dart-Packages#18]
**I get the follow error when I try to get something from the API:**
Error: DioError [DioErrorType.RESPONSE]: XMLHttpRequest error.
    C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/patch/core_patch.dart 906:28                get current
packages/dio/src/adapters/browser_adapter.dart 79:20                                                                           <fn>
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/zone.dart 1446:54                                              runUnary
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/future_impl.dart 150:18                                        handleValue
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/future_impl.dart 703:44                                        handleValueCallback
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/future_impl.dart 732:32                                        _propagateToListeners
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/future_impl.dart 526:7                                         [_complete]
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/stream_pipe.dart 61:11                                         _cancelAndValue
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/stream.dart 1302:7                                             <fn>
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 324:14  _checkAndCall
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 329:39  dcall
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/html/dart2js/html_dart2js.dart 37307:58                              <fn>
    at Object.createErrorWithStack (http://localhost:51253/dart_sdk.js:4375:12)
    at Object._rethrow (http://localhost:51253/dart_sdk.js:38296:16)
    at async._AsyncCallbackEntry.new.callback (http://localhost:51253/dart_sdk.js:38290:13)
    at Object._microtaskLoop (http://localhost:51253/dart_sdk.js:38122:13)
    at _startMicrotaskLoop (http://localhost:51253/dart_sdk.js:38128:13)
    at http://localhost:51253/dart_sdk.js:33625:9

**Output of flutter doctor -v:**
[√] Flutter (Channel beta, 1.25.0-8.3.pre, on Microsoft Windows [Version 10.0.18363.1316], locale en-US)
    • Flutter version 1.25.0-8.3.pre at E:\Documents\Programming\Flutter\flutter
    • Framework revision 5d36f2e7f5 (2 weeks ago), 2021-01-14 15:57:49 -0800
    • Engine revision 7a8f8ca02c
    • Dart version 2.12.0 (build 2.12.0-133.7.beta)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\flyer_zf1eab6\AppData\Local\Android\Sdk
    • Platform android-30, build-tools 28.0.3
    • ANDROID_HOME = C:\Users\flyer_zf1eab6\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 3.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[√] VS Code (version 1.52.1)
    • VS Code at C:\Users\flyer_zf1eab6\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.19.0

[√] VS Code, 64-bit edition (version 1.45.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.19.0

[√] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 88.0.4324.104
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 88.0.705.50

**Comment by JagandeepBrar** [comment]
This looks like it may be an upstream issue with the Dio package itself, you can view here: https://github.com/flutterchina/dio/issues/750

The underlying engine that makes the request doesn't return any additional information about what the error is sadly. Can you check the console in your web browser when this error is made to see if any additional information is printed?

Did you ensure you set your CORS headers on your machine hosting the Tautulli instance? It appears that solved the issue for many users. I would also recommend that you create a quick native dart file to test that the connection to Tautulli works itself.

**Comment by JagandeepBrar** [comment]
I am going to assume that this issue has been solved. If you're still having problems, feel free to reopen this issue or a new one.
